import type { ModeKey } from './types';

/*
 * The movement library the importer matches against.
 *
 * Extracted verbatim from the vanilla app's IMP_LIB_RAW so no alias is lost in
 * transcription — an alias that goes missing does not fail loudly, it just
 * quietly stops recognising someone's shorthand.
 *
 * Shape: [canonical name, mode, aliases].
 */
export const IMP_LIB_RAW: [string, ModeKey, string[]][] = [
  ["Back squat", "reps_kg", ["squat", "squats", "bb squat", "back squats", "high bar squat", "low bar squat"]],
  ["Front squat", "reps_kg", ["front squats", "fs"]],
  ["Overhead squat", "reps_kg", ["ohs", "overhead squats"]],
  ["Box squat", "reps_kg", ["box squats"]],
  ["Deadlift", "reps_kg", ["dl", "deadlifts", "deads", "conventional deadlift"]],
  ["Romanian deadlift", "reps_kg", ["rdl", "rdls", "romanian deadlifts", "stiff leg deadlift", "sldl"]],
  ["Sumo deadlift", "reps_kg", ["sumo", "sumo deadlifts"]],
  ["Trap bar deadlift", "reps_kg", ["trap bar", "hex bar deadlift", "trap bar deadlifts"]],
  ["Bench press", "reps_kg", ["bench", "bb bench", "flat bench", "benchpress"]],
  ["Incline bench press", "reps_kg", ["incline bench", "incline press", "incline bb press"]],
  ["Close grip bench press", "reps_kg", ["cgbp", "close grip bench"]],
  ["Overhead press", "reps_kg", ["ohp", "press", "shoulder press", "military press", "strict press"]],
  ["Push press", "reps_kg", ["push presses"]],
  ["Barbell row", "reps_kg", ["bb row", "bent over row", "pendlay row", "barbell rows", "bor"]],
  ["Hip thrust", "reps_kg", ["hip thrusts", "bb hip thrust"]],
  ["Good morning", "reps_kg", ["good mornings", "gm"]],
  ["Clean", "reps_kg", ["power clean", "cleans", "hang clean", "squat clean", "power cleans"]],
  ["Clean and jerk", "reps_kg", ["c&j", "clean & jerk", "clean and jerks"]],
  ["Snatch", "reps_kg", ["power snatch", "snatches", "hang snatch"]],
  ["Thruster", "reps_kg", ["thrusters"]],
  ["Front rack lunge", "reps_kg", ["front rack lunges"]],
  ["Barbell curl", "reps_kg", ["bb curl", "barbell curls"]],
  ["Dumbbell bench press", "reps_kg", ["db bench", "db press", "db bench press", "dumbbell press"]],
  ["Incline dumbbell press", "reps_kg", ["incline db press", "incline db bench", "incline dumbbell bench"]],
  ["Dumbbell row", "reps_kg", ["db row", "db rows", "single arm row", "one arm row"]],
  ["Dumbbell shoulder press", "reps_kg", ["db shoulder press", "db ohp", "seated db press"]],
  ["Dumbbell curl", "reps_kg", ["db curl", "db curls", "bicep curl", "bicep curls", "curls"]],
  ["Hammer curl", "reps_kg", ["hammer curls"]],
  ["Lateral raise", "reps_kg", ["lateral raises", "side raise", "side raises", "lat raise"]],
  ["Dumbbell fly", "reps_kg", ["db fly", "db flys", "chest fly", "flyes"]],
  ["Goblet squat", "reps_kg", ["goblet squats"]],
  ["Dumbbell lunge", "reps_kg", ["db lunge", "db lunges"]],
  ["Dumbbell romanian deadlift", "reps_kg", ["db rdl", "db rdls"]],
  ["Kettlebell swing", "reps", ["kb swing", "kb swings", "kettlebell swings", "swing", "swings", "russian swing"]],
  ["Kettlebell snatch", "reps", ["kb snatch", "kb snatches"]],
  ["Kettlebell clean and press", "reps", ["kb clean and press", "kb clean & press"]],
  ["Turkish get-up", "reps", ["tgu", "turkish getup", "turkish get ups", "get up", "get-ups"]],
  ["Devils press", "reps", ["devil press", "devil’s press", "devils presses"]],
  ["Dumbbell snatch", "reps", ["db snatch", "db snatches", "alt db snatch"]],
  ["Lat pulldown", "reps_kg", ["pulldown", "pulldowns", "lat pull down"]],
  ["Seated cable row", "reps_kg", ["cable row", "cable rows", "seated row", "low row"]],
  ["Cable fly", "reps_kg", ["cable flys", "cable crossover"]],
  ["Tricep pushdown", "reps_kg", ["pushdown", "pushdowns", "rope pushdown", "tricep extension"]],
  ["Face pull", "reps_kg", ["face pulls", "facepull"]],
  ["Leg press", "reps_kg", ["leg presses"]],
  ["Leg extension", "reps_kg", ["leg extensions"]],
  ["Leg curl", "reps_kg", ["leg curls", "hamstring curl", "ham curl"]],
  ["Calf raise", "reps_kg", ["calf raises", "calves"]],
  ["Chest supported row", "reps_kg", ["chest supported rows", "seal row"]],
  ["Hack squat", "reps_kg", ["hack squats"]],
  ["Pull-up", "reps", ["pull up", "pullup", "pull-ups", "pullups", "pull ups", "chin up", "chin-up", "chins", "chinups"]],
  ["Push-up", "reps", ["push up", "pushup", "push-ups", "pushups", "push ups", "press up", "press-ups", "press ups"]],
  ["Dip", "reps", ["dips", "ring dip", "ring dips", "bar dip", "bar dips"]],
  ["Ring row", "reps", ["ring rows", "inverted row", "inverted rows"]],
  ["Muscle-up", "reps", ["muscle up", "muscle ups", "ring muscle up", "bar muscle up", "mu"]],
  ["Handstand push-up", "reps", ["hspu", "handstand pushup", "handstand push ups"]],
  ["Wall walk", "reps", ["wall walks", "wallwalk", "wall-walk"]],
  ["Burpee", "reps", ["burpees", "burpee over bar", "bar facing burpee"]],
  ["Air squat", "reps", ["air squats", "bodyweight squat", "bw squat"]],
  ["Lunge", "reps", ["lunges", "walking lunge", "walking lunges", "reverse lunge", "reverse lunges"]],
  ["Box jump", "reps", ["box jumps", "box jump over"]],
  ["Jump squat", "reps", ["jump squats"]],
  ["Broad jump", "reps", ["broad jumps"]],
  ["Step-up", "reps", ["step up", "step ups", "box step up", "box step-ups"]],
  ["Sit-up", "reps", ["sit up", "situp", "sit-ups", "situps", "sit ups", "abmat sit up"]],
  ["V-up", "reps", ["v up", "v ups", "vups"]],
  ["Toes-to-bar", "reps", ["toes to bar", "ttb", "t2b"]],
  ["Knees-to-elbow", "reps", ["knees to elbow", "k2e"]],
  ["Hanging knee raise", "reps", ["knee raises", "hanging knee raises", "leg raise", "leg raises", "hanging leg raise"]],
  ["Mountain climber", "reps", ["mountain climbers", "climbers"]],
  ["Wall ball", "reps", ["wall balls", "wallball", "wallballs", "wb"]],
  ["Slam ball", "reps", ["slam balls", "ball slam", "ball slams", "med ball slam"]],
  ["Russian twist", "reps", ["russian twists"]],
  ["Back extension", "reps", ["back extensions", "hyperextension", "hyperextensions", "45 degree back extension"]],
  ["Glute bridge", "reps", ["glute bridges"]],
  ["Nordic curl", "reps", ["nordic curls", "nordics"]],
  ["Pistol squat", "reps", ["pistol", "pistols", "pistol squats"]],
  ["Band pull-apart", "reps", ["band pull aparts", "band pull apart", "pull aparts"]],
  ["Scap push-up", "reps", ["scap pushup", "scap push ups", "scap pushups"]],
  ["Plank", "seconds", ["planks", "front plank", "plank hold"]],
  ["Side plank", "seconds", ["side planks"]],
  ["Dead hang", "seconds", ["deadhang", "dead hangs", "hang", "bar hang"]],
  ["Hollow hold", "seconds", ["hollow", "hollow holds", "hollow body hold"]],
  ["Wall sit", "seconds", ["wall sits", "wall sit hold"]],
  ["L-sit", "seconds", ["l sit", "l-sits", "l sits"]],
  ["Handstand hold", "seconds", ["handstand holds", "hs hold", "wall handstand hold"]],
  ["Farmer carry", "seconds", ["farmers carry", "farmer walk", "farmers walk", "farmer hold", "farmers hold", "carry", "carries"]],
  ["Suitcase carry", "seconds", ["suitcase carries"]],
  ["Overhead carry", "seconds", ["oh carry", "overhead carries", "waiter carry"]],
  ["Sled push", "seconds", ["sled pushes", "prowler", "prowler push"]],
  ["Sled drag", "seconds", ["sled drags"]],
  ["Cardio", "seconds", ["cardio of choice", "bike", "assault bike", "echo bike", "air bike", "ski", "ski erg", "skierg", "row erg", "rower", "erg", "run", "running", "jog", "treadmill", "skip", "skipping", "jump rope", "double unders", "singles", "shuttle runs", "shuttles"]],
  ["Bike (calories)", "reps", ["cal bike", "cals bike", "bike cals", "cal assault bike", "cal echo bike"]],
  ["Row (calories)", "reps", ["cal row", "cals row", "row cals"]],
  ["Ski (calories)", "reps", ["cal ski", "cals ski", "ski cals"]],
  ["Run (metres)", "reps", ["m run", "metre run", "meter run"]],
  ["Row (metres)", "reps", ["m row", "metre row", "meter row"]],
];

/** name/alias (lowercased) → canonical entry. Built once at module load. */
export const IMP_ALIAS: Record<string, { name: string; mode: ModeKey }> = {};
IMP_LIB_RAW.forEach((e) => {
  IMP_ALIAS[e[0].toLowerCase()] = { name: e[0], mode: e[1] };
  e[2].forEach((a) => {
    IMP_ALIAS[a] = { name: e[0], mode: e[1] };
  });
});
