import { config, requireConfig } from './config.mjs';
const AUTH = 'https://www.strava.com/oauth'; const API = 'https://www.strava.com/api/v3';
export function createStravaAuthUrl(state) { requireConfig('stravaClientId'); const u = new URL(`${AUTH}/authorize`); u.search = new URLSearchParams({ client_id: config.stravaClientId, response_type: 'code', redirect_uri: config.stravaCallback, approval_prompt: 'auto', scope: 'activity:read_all', state }).toString(); return u.toString(); }
async function tokenRequest(body) { requireConfig('stravaClientId', 'stravaClientSecret'); const r = await fetch(`${AUTH}/token`, { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ client_id: config.stravaClientId, client_secret: config.stravaClientSecret, ...body }) }); if (!r.ok) throw new Error(`Strava token request failed (${r.status})`); return r.json(); }
export const exchangeStravaCode = (code) => tokenRequest({ grant_type: 'authorization_code', code });
export const refreshStravaToken = (refresh_token) => tokenRequest({ grant_type: 'refresh_token', refresh_token });
export async function stravaFetch(path, token) { const r = await fetch(`${API}${path}`, { headers: { authorization: `Bearer ${token}` } }); if (!r.ok) throw new Error(`Strava API request failed (${r.status})`); return r.json(); }
export function normalizeStravaActivity(input = {}) { const n = (v) => Number.isFinite(Number(v)) ? Number(v) : null; return { source: 'strava', id: input.id || null, date: String(input.start_date_local || input.start_date || '').slice(0, 10), sportType: input.sport_type || input.type || 'Workout', durationSec: n(input.elapsed_time), movingTimeSec: n(input.moving_time), distanceM: n(input.distance), elevationM: n(input.total_elevation_gain), averageSpeedMps: n(input.average_speed), averageHr: n(input.average_heartrate), averageWatts: n(input.average_watts), capturedAt: new Date().toISOString() }; }
export async function fetchStravaSnapshot(token) { const activities = await stravaFetch('/athlete/activities?per_page=30', token); return { activities: activities.map(normalizeStravaActivity), syncedAt: new Date().toISOString() }; }
